### PR TITLE
Improve unit tests

### PR DESCRIPTION
**Pull request by jlorentson**
Related to Issue #21.
I think the behavior of our code is pretty well tested. The problems we have been having with failing unit tests in SEER*DMS have to do with changes to the AGGIE service; usually about how match scores are calculated. Because we want to know when things like that happen (without every branch of DMS constantly failing unit tests), I added checks to every field returned by AGGIE, based on the  examples they include in their documentation. I added tests for the `confidenceLevels` and `shouldDoExhaustiveSearch` parameters, though it's not clear to me that the former is doing anything.

There are probably more conditions that could be tested but this seems like a good starting point. Thoughts?

### CODE REVIEW

**Comment by criderp** [comment]
That sounds good to me. So, what are the next steps? Running these tests at regular intervals and cleaning up the DMS tests?

**Comment by jlorentson** [comment]
Yeah. I don't think we need to be geocoding addresses in DMS tests; maybe just to make sure it connects and returns a result. I haven't look much at cleaning up DMS yet but we can start a squish issue. If we release after this gets merged we'll need to make a couple changes to DMS because of the change to census years in MR #22.

**Comment by ctmay4** [comment]
Are you asking me or Philip?  I would definitely like to tone down the tests in DMS.  Just some very basic ones to make sure we can communicate with the service.   

Once you merge this issue, I think you should set this up to run every night.

**Comment by jlorentson** [comment]
I was asking both! I think with these tests running nightly we can rewrite the unit tests in DMS to be a lot less brittle; like you said, just making sure it's connecting.

I don't have write access; I need someone to review & merge, and then release if we agree it's ready.

**Pull request merged**
